name: My First CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from my first CI pipeline!"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
